spring:
  #jpa设置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  #http
  http:
    encoding:
      charset: utf-8
  #日志颜色
  output:
    ansi:
      enabled: always
  #开启aop使用jdk代理
  aop:
    auto: true
  redis:
    port: 6379
  profiles:
    include: datasource
server:
  context-path: /ryze
  port: 80
